inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  SuggestExtensions: false

Rails/FilePath:
  Enabled: false
Rails/Output:
  Enabled: false

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
  Exclude:
    - "app/controllers/**/*"

Style/Documentation:
  Enabled: false
