inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable

Rails/FilePath:
  Enabled: false
Rails/Output:
  Enabled: false

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
