inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  SuggestExtensions: false

Rails/FilePath:
  Enabled: false

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
  Exclude:
    - "app/controllers/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 45

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 11

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"

Rails/I18nLocaleTexts:
  Enabled: false

Rails/TransactionExitStatement:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/ContextWording:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: true
